watch_stylesheet: true
watch_config: true
debug: false
bars:
  primary-bar:
    enabled: true
    screens: ['VG279QR'] 
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: false
    blur_effect:
      enabled: false
      acrylic: true
      dark_mode: true
      round_corners: true
    window_flags:
      always_on_top: true
      windows_app_bar: true
      hide_on_fullscreen: true
    dimensions:
      width: "100%"
      height: 31
    padding:
      top: 14 # 4 4 2 4
      left: 17
      bottom: 0
      right: 17
    widgets:
      left:
        [
          "grouped_widgets_1"
        ]
      center:
        [
          "grouped_widgets_2"
        ]
      right:
        [
          "grouped_widgets_3"
        ]
widgets:
  home:
    type: "yasb.home.HomeWidget"
    options:
      label: ""
      menu_list:
      - { title: "Home", path: "~" }
      - { title: "Downloads", path: "C:\\Users\\Darren\\Downloads"}
      - { title: "Documents", path: "C:\\Users\\Darren\\Documents"}
      - { title: "Pictures", path: "C:\\Users\\Darren\\Pictures"}
      - { title: "Videos", path: "C:\\Users\\Darren\\Videos"}
      system_menu: true
      power_menu: false
      blur: false
      round_corners: true
      round_corners_type: "normal"
      distance: 5
      container_padding: 
        top: 0
        left: 0
        bottom: 0
        right: 0
      alignment: "left"
      direction: "down"
      menu_labels:
        shutdown: "Shutdown"
        restart: "Restart"
        logout: "Logout"
        lock: "Lock"
        sleep: "Sleep"
        system: "System Settings"
        about: "About This PC"
        task_manager: "Task Manager"

  weather:
    type: "yasb.weather.WeatherWidget"
    options:
      label: "<span>{icon}</span> {temp}"
      label_alt: "<span>{icon}</span> {location}: Min {min_temp}, Max {max_temp}, Humidity {humidity}"
      api_key: 'EnterAPIKeyHere'
      update_interval: 600 #Update interval in seconds, Min 600
      hide_decimal: true
      location: 'Irkutsk'
      callbacks:
        on_left: "toggle_label"
      icons:
        sunnyDay: "\udb81\udd99"
        clearNight: "\udb81\udd99"
        cloudyDay: "\udb81\udd99"
        cloudyNight: "\udb81\udd99"
        rainyDay: "\udb81\udd99"
        rainyNight: "\udb81\udd99"
        snowyIcyDay: "\udb81\udd99"
        snowyIcyNight: "\udb81\udd99"
        blizzardDay: "\udb81\udd99"
        default: "\udb81\udd99" 
  media:
      type: "yasb.media.MediaWidget"
      options:
        label: "{artist} - {title}"
        label_alt: "{artist}"
        callbacks:
          on_left: "toggle_media_menu"
          on_middle: "do_nothing"
          on_right: "toggle_label"
        max_field_size:
          label: 45
          label_alt: 45
        show_thumbnail: false
        controls_only: false
        controls_left: true
        hide_empty: false
        thumbnail_alpha: 250
        thumbnail_padding: 8
        thumbnail_corner_radius: 6
        icons:
          prev_track: ""
          next_track: ""
          play: "<span>\uf001</span>"
          pause: "<span>\uf001</span>"
        media_menu:
          blur: false
          round_corners: true
          round_corners_type: "normal"
          alignment: "left"
          direction: "down"
          offset_top: 5
          offset_left: 0
          thumbnail_size: 90
          thumbnail_corner_radius: 6
          max_title_size: 60
          max_artist_size: 50
          show_source: true
        media_menu_icons:
          play: "\ue768"
          pause: "\ue769"
          prev_track: "\ue892"
          next_track: "\ue893"
  active_window:
    type: "yasb.active_window.ActiveWindowWidget"
    options:
      label: "{win[title]}"
      label_alt: "[class_name='{win[class_name]}' exe='{win[process][name]}' hwnd={win[hwnd]}]"
      label_no_window: ""
      label_icon: false
      label_icon_size: 14
      max_length: 36
      max_length_ellipsis: "..."
      monitor_exclusive: true
  volume:
    type: "yasb.volume.VolumeWidget"
    options:
      label: " "
      label_alt: ""
      tooltip: True
      volume_icons:
        - "󰖁 "  # Icon for muted
        - "󰕿 "  # Icon for 0-10% volume
        - "󰖀 "  # Icon for 11-30% volume
        - "󰖀 "  # Icon for 31-60% volume
        - "󰕾 "  # Icon for 61-100% volume
      progress_bar:
        enabled: True
        position: 'right'
        size: 16
        thickness: 3
        color: '#d6d7db'
        animation: False
      audio_menu:
        blur: True
        round_corners: True
        round_corners_type: "normal"
        border_color: "system"
        alignment: "center"
        direction: "down"
      callbacks:
        on_left: "toggle_volume_menu"
        on_right: "exec cmd.exe /c start ms-settings:sound"
  clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "{%H:%M}"
      label_alt: "{%d/%m/%y %H:%M}"
      tooltip: false
      timezones: []
      calendar:
        alignment: "right"
        direction: "down"
  disk:
    type: "yasb.disk.DiskWidget"
    options:
        label: "<span>\uf473</span>"
        label_alt: "<span>\uf473</span>"
        update_interval: 60
        group_label:
          volume_labels: ["C", "D", "E", "F"]
          show_label_name: false
          blur: True
          round_corners: True
          round_corners_type: "small"
          border_color: "System"
          alignment: "right"
          direction: "up"
          distance: 6
        callbacks:
          on_left: "toggle_group"
          on_middle: "toggle_label"
          on_right: "exec explorer C:\\" # Open disk C in file explorer
  wallpapers:
    type: "yasb.wallpapers.WallpapersWidget"
    options:
      label: "<span>\udb83\ude09</span>"
      image_path: "C:\\Users\\Darren\\iCloudDrive\\Wallpapers\\Themes\\Monochrome"
      change_automatically: false
      update_interval: 60
      animation:
        enabled: true
        type: 'fadeInOut'
        duration: 200      
      gallery:
        enabled: true
        blur: true
        image_width: 296
        image_per_page: 6
        show_buttons: true
        orientation: "portrait"
        image_spacing: 10
        lazy_load: true
        lazy_load_delay: 10
        lazy_load_fadein: 200
        image_corner_radius: 0
        enable_cache: true
  power_menu:
      type: "yasb.power_menu.PowerMenuWidget"
      options:
        label: "⏻"
        uptime: True
        blur: False
        blur_background: True
        animation_duration: 200 # Milisecond 
        button_row: 5 # Number of buttons in row, min 1 max 5
        buttons:
          signout: ["󰍃","Sign out"]
          shutdown: ["","Shut Down"]
          restart: ["","Restart"]
          hibernate: ["","Hibernate"]
          cancel: ["","Cancel"]
  cava:
    type: "yasb.cava.CavaWidget"
    options:
      bar_height: 12
      gradient: 0
      reverse: 0
      sensitivity: 80
      foreground: "#d6d7db"
      gradient_color_1: '#d6d7db'
      gradient_color_2: '#d6d7db'
      gradient_color_3: '#d6d7db'
      bars_number: 6
      bar_spacing: 2
      bar_width: 1
      sleep_timer: 0
      hide_empty: true
      container_padding:
        top: 0
        left: 2
        bottom: 0
        right: 0
  brightness:
    type: "yasb.brightness.BrightnessWidget"
    options:
      label: ""
      label_alt: ""
      tooltip: True
      hide_unsupported: True
      brightness_toggle_level: [0, 50, 100]
      auto_light: False
      auto_light_icon: "\udb80\udce1"
      auto_light_night_level: 35
      auto_light_night_start_time: "19:00"
      auto_light_night_end_time: "06:45"
      auto_light_day_level: 75
      brightness_icons: [
        "\udb85\udce4",  # 0-25%
        "\udb80\udcdc",  # 26-50% 
        "\udb80\udcdb",  # 51-75%
        "\udb80\udcda"   # 76-100%
      ]
      progress_bar:
        enabled: True
        position: 'right'
        size: 16
        thickness: 3
        color: '#d6d7db'
        animation: False
      brightness_menu:
        blur: True
        round_corners: True
        round_corners_type: "normal"
        border_color: "system"
        alignment: "right"
        direction: "down"
      callbacks:
          on_left: "toggle_brightness_menu"
  github:
    type: "yasb.github.GithubWidget"
    options:
      label: "<span>\ueba1</span>"
      label_alt: "Notifications {data}" # {data} return number of unread notification
      token: env # GitHub Personal access tokens (classic) https://github.com/settings/tokens
      max_notification: 20 # Max number of notification displaying in menu max: 50
      only_unread: false # Show only unread or all notifications; 
      max_field_size: 54 # Max characters in title before truncation.
      update_interval: 300 # Check for new notification in seconds
      menu:
        blur: True # Enable blur effect for the menu
        round_corners: True # Enable round corners for the menu (this option is not supported on Windows 10)
        round_corners_type: "normal" # Set the type of round corners for the menu (normal, small) (this option is not supported on Windows 10)
        border_color: "System" # Set the border color for the menu (this option is not supported on Windows 10)
        alignment: "right"
        direction: "up"
        distance: 6
  komorebi_active_layout:
    type: "komorebi.active_layout.ActiveLayoutWidget"
    options:
      hide_if_offline: true
      label: "{layout_name}"
      layouts: ['bsp', 'columns', 'rows', 'grid', 'vertical_stack', 'horizontal_stack', 'ultrawide_vertical_stack','right_main_vertical_stack']
      layout_icons:
        bsp: "\uebeb"
        columns: "\uebf7"
        rows: "\uec01"
        grid: "\udb81\udf58"
        scrolling: "\uebf7"
        vertical_stack: "\uebee"
        horizontal_stack: "\uebf0"
        ultrawide_vertical_stack: "\uebee"
        right_main_vertical_stack: "\uebf1"
        monocle: "\uf06f"
        maximized: "\uf06f"
        floating: "\uf2d2"
        paused: "\udb83\udf89"
        tiling: "\udb81\ude40"
      callbacks:
        on_left: 'toggle_layout_menu'
        on_middle: 'next_layout'
        on_right: 'prev_layout'
      layout_menu:
        blur: false
        round_corners: true
        round_corners_type: "normal"
        border_color: "System"
        alignment: "left"
        direction: "up"
        offset_top: 5
        offset_left: 5
        show_layout_icons: true
      label_shadow:
        enabled: false
        color: "black"
        radius: 3
        offset: [ 1, 1 ]
  apps:
      type: "yasb.applications.ApplicationsWidget"
      options:
        label: "{data}"
        app_list:
          - {icon: "", launch: "explorer shell:MyComputerFolder"}
          #- {icon: "\udb80\ude39", launch: "C:\\Program Files\\Mozilla Firefox\\firefox.exe"}
          - {icon: "", launch: "notification_center"}
          # Currently available to use quick_settings, notification_center, search, widget, launcher (launcher will trigger ALT+A)
        container_padding: 
          top: 0
          left: 0
          bottom: 0
          right: 0
  komorebi_workspaces:
    type: "komorebi.workspaces.WorkspaceWidget"
    options:
      label_offline: " "
      label_workspace_btn: ""
      label_workspace_active_btn: ""
      label_workspace_populated_btn: ""
      label_default_name: "{index}"
      label_zero_index: false
      hide_empty_workspaces: false
      hide_if_offline: false
      animation: true
  systray:
    type: "yasb.systray.SystrayWidget"
    options:
      class_name: "systray"
      label_collapsed: "󰇘"
      label_expanded: "󰇘"
      show_unpinned: false
      show_unpinned_button: true
      show_battery: false
      show_volume: false
      pin_click_modifier: 'ctrl'
      show_network: false
      btn_shadow:
        enabled: true
        color: "black"
        radius: 3
        offset: [ 1, 1 ]
  taskbar:
    type: "yasb.taskbar.TaskbarWidget"
    options:
      icon_size: 15
      tooltip: true
      show_only_visible: false
      strict_filtering: true
      monitor_exclusive: false
      animation:
        enabled: true
        type: fadeInOut
        duration: 50
      preview:
        enabled: true
        width: 240
        delay: 400
        padding: 10
        margin: 15
      title_label:
        enabled: true
        show: "focused"
        min_length: 0
        max_length: 30
      ignore_apps:
        processes: []
        titles: []
        classes: []
  pomodoro:
    type: "yasb.pomodoro.PomodoroWidget"
    options:
      label: "<span>{icon}</span> {remaining}"
      label_alt: "<span>{icon}</span> {session}/{total_sessions} - {status}"
      work_duration: 25
      break_duration: 5
      long_break_duration: 15
      long_break_interval: 4
      auto_start_breaks: true
      auto_start_work: true
      sound_notification: true
      show_notification: true
      hide_on_break: false
      session_target: 8
      icons:
        work: "\uf252"
        break: "\uf253"
        paused: "\uf254"
      menu:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "System"
        alignment: "right"
        direction: "down"
        offset_top: 6
        offset_left: 0
        circle_background_color: "#09ffffff"
        circle_work_progress_color: "#88c0d0"
        circle_break_progress_color: "#a3be8c"
        circle_thickness: 8
        circle_size: 160
      callbacks:
        on_left: "toggle_menu"
        on_middle: "reset_timer"
        on_right: "toggle_label"
      label_shadow:
        enabled: true
        color: "black"
        radius: 3
        offset: [ 1, 1 ]
  grouped_widgets_1:
    type: "yasb.grouper.GrouperWidget"
    options:
      class_name: "grouped-widgets"
      widgets: [
        "home",
        "komorebi_workspaces",
        "media",
        "cava",
        "hidden"
      ]
  grouped_widgets_2:
    type: "yasb.grouper.GrouperWidget"
    options:
      class_name: "grouped-widgets"
      widgets: [
        "taskbar"
      ]
  grouped_widgets_3:
    type: "yasb.grouper.GrouperWidget"
    options:
      class_name: "grouped-widgets"
      widgets: [
        "hidden",
        "systray",
        "apps",
        "lines",
        "brightness",
        "volume",
        "lines",
        "clock",
        "lines",
        "power_menu"
      ]
  lines:
    type: "yasb.custom.CustomWidget"
    options:
      label: "\u007c"
      label_alt: "\u007c"
      class_name: "separator-widget"
      callbacks:
        on_left: "do_nothing"
  win_button:
      type: "yasb.custom.CustomWidget"
      options:
        label: "\ue62a"
        label_alt: "\ue62a"
        class_name: "system-widget"
        callbacks:
          on_left: "exec start_menu"

  hidden:
    type: "yasb.custom.CustomWidget"
    options:
      label: "\u007c"
      label_alt: "\u007c"
      class_name: "clear-widget"
      callbacks:
        on_left: "do_nothing"
